const RouteView = {
    name: 'RouteView',
    render: h => h('router-view'),
};

/**
 * 基础路由
 * @type { *[] }
 */
const constantRouters = {
    path: '/launch-demo2',
    name: 'launch-demo2',
    meta: { title: '教学管理系统', keepAlive: true, icon: 'setting' },
    component: () => import('@/view/launch-demo2/index/Index.vue'),
    redirect: '/launch-demo2/basic/shift',
    children: [
        {
            path: '/launch-demo2/basic',
            name: 'launch-demo2-basic',
            component: RouteView,
            hidden: true,
            meta: { title: '基础信息', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/basic/shift',
                    name: 'launch-demo2-basic-shift',
                    component: () => import('@/view/launch-demo2/basic/shift/Index.vue'),
                    hidden: true,
                    meta: { title: '班次信息', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/basic/semester',
                    name: 'launch-demo2-basic-semester',
                    component: () => import('@/view/launch-demo2/basic/semester/Index.vue'),
                    hidden: true,
                    meta: { title: '学期信息', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/basic/review',
                    name: 'launch-demo2-basic-review',
                    component: () => import('@/view/launch-demo2/basic/review/Index.vue'),
                    hidden: true,
                    meta: { title: '评审信息', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/basic/bidding',
                    name: 'launch-demo2-basic-bidding',
                    component: () => import('@/view/launch-demo2/basic/bidding/Index.vue'),
                    hidden: true,
                    meta: { title: '招标模块', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/basic/reviewItems',
                    name: 'launch-demo2-basic-reviewItems',
                    component: () => import('@/view/launch-demo2/basic/reviewItems/Index.vue'),
                    hidden: true,
                    meta: { title: '评审项目', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/teachingResources',
            name: 'launch-demo2-teachingResources',
            component: RouteView,
            hidden: true,
            meta: { title: '教学资源', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/teachingResources/teacherLibrary',
                    name: 'launch-demo2-teachingResources-teacherLibrary',
                    component: () => import('@/view/launch-demo2/teachingResources/teacherLibrary/Index.vue'),
                    hidden: true,
                    meta: { title: '师资库', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingResources/thematicLibrary',
                    name: 'launch-demo2-teachingResources-thematicLibrary',
                    component: () => import('@/view/launch-demo2/teachingResources/thematicLibrary/Index.vue'),
                    hidden: true,
                    meta: { title: '专题库', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingResources/teachingActivities',
                    name: 'launch-demo2-teachingResources-teachingActivities',
                    component: () => import('@/view/launch-demo2/teachingResources/teachingActivities/Index.vue'),
                    hidden: true,
                    meta: { title: '教学活动', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingResources/teachingSite',
                    name: 'launch-demo2-teachingResources-teachingSite',
                    component: () => import('@/view/launch-demo2/teachingResources/teachingSite/Index.vue'),
                    hidden: true,
                    meta: { title: '教学场地', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingResources/classFund',
                    name: 'launch-demo2-teachingResources-classFund',
                    component: () => import('@/view/launch-demo2/teachingResources/classFund/Index.vue'),
                    hidden: true,
                    meta: { title: '办班经费', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingResources/elective',
                    name: 'launch-demo2-teachingResources-elective',
                    component: () => import('@/view/launch-demo2/teachingResources/elective/Index.vue'),
                    hidden: true,
                    meta: { title: '选修课管理', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/educationalManage',
            name: 'launch-demo2-educationalManage',
            component: RouteView,
            hidden: true,
            meta: { title: '教务管理', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/educationalManage/teacherLibrary',
                    name: 'launch-demo2-educationalManage-teacherLibrary',
                    component: () => import('@/view/launch-demo2/educationalManage/teacherLibrary/Index.vue'),
                    hidden: true,
                    meta: { title: '班次文档', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/educationalManage/fileMould',
                    name: 'launch-demo2-educationalManage-fileMould',
                    component: () => import('@/view/launch-demo2/educationalManage/fileMould/Index.vue'),
                    hidden: true,
                    meta: { title: '文档模板', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/educationalManage/curriculum',
                    name: 'launch-demo2-educationalManage-curriculum',
                    component: () => import('@/view/launch-demo2/educationalManage/curriculum/Index.vue'),
                    hidden: true,
                    meta: { title: '课程表', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/educationalManage/curriculumEvaluation',
                    name: 'launch-demo2-educationalManage-curriculumEvaluation',
                    component: () => import('@/view/launch-demo2/educationalManage/curriculumEvaluation/Index.vue'),
                    hidden: true,
                    meta: { title: '课表评估设置', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/educationalManage/timetableQuery',
                    name: 'launch-demo2-educationalManage-timetableQuery',
                    component: () => import('@/view/launch-demo2/educationalManage/timetableQuery/Index.vue'),
                    hidden: true,
                    meta: { title: '课表查询', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/specialReview',
            name: 'launch-demo2-specialReview',
            component: RouteView,
            hidden: true,
            meta: { title: '专题评审', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/specialReview/publishTopics',
                    name: 'launch-demo2-specialReview-publishTopics',
                    component: () => import('@/view/launch-demo2/specialReview/publishTopics/Index.vue'),
                    hidden: true,
                    meta: { title: '发布新专题', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/specialReview/specialDeclaration',
                    name: 'launch-demo2-specialReview-specialDeclaration',
                    component: () => import('@/view/launch-demo2/specialReview/specialDeclaration/Index.vue'),
                    hidden: true,
                    meta: { title: '专题申报', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/specialReview/lectureReview',
                    name: 'launch-demo2-specialReview-lectureReview',
                    component: () => import('@/view/launch-demo2/specialReview/lectureReview/Index.vue'),
                    hidden: true,
                    meta: { title: '试讲评审', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/specialReview/reviewManage',
                    name: 'launch-demo2-specialReview-reviewManage',
                    component: () => import('@/view/launch-demo2/specialReview/reviewManage/Index.vue'),
                    hidden: true,
                    meta: { title: '评审管理', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/courseActivityQuery',
            name: 'launch-demo2-courseActivityQuery',
            component: RouteView,
            hidden: true,
            meta: { title: '任课活动查询', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/courseActivityQuery/courseQuery',
                    name: 'launch-demo2-courseActivityQuery-courseQuery',
                    component: () => import('@/view/launch-demo2/courseActivityQuery/courseQuery/Index.vue'),
                    hidden: true,
                    meta: { title: '任课活动查询', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/curriculumManege',
            name: 'launch-demo2-curriculumManege',
            component: RouteView,
            hidden: true,
            meta: { title: '课程管理', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/curriculumManege/classReminder',
                    name: 'launch-demo2-curriculumManege-classReminder',
                    component: () => import('@/view/launch-demo2/curriculumManege/classReminder/Index.vue'),
                    hidden: true,
                    meta: { title: '上课提醒', keepAlive: true, icon: 'global' },
                },
                // {
                //     path: '/launch-demo2/curriculumManege/reminderSettings',
                //     name: 'launch-demo2-curriculumManege-reminderSettings',
                //     component: () => import('@/view/launch-demo2/curriculumManege/reminderSettings/Index.vue'),
                //     hidden: true,
                //     meta: { title: '提醒设置', keepAlive: true, icon: 'global' },
                // },
                // {
                //     path: '/launch-demo2/curriculumManege/courseAdjustment',
                //     name: 'launch-demo2-curriculumManege-courseAdjustment',
                //     component: () => import('@/view/launch-demo2/curriculumManege/courseAdjustment/Index.vue'),
                //     hidden: true,
                //     meta: { title: '调课提醒', keepAlive: true, icon: 'global' },
                // },
                {
                    path: '/launch-demo2/curriculumManege/departmentReplacement',
                    name: 'launch-demo2-curriculumManege-departmentReplacement',
                    component: () => import('@/view/launch-demo2/curriculumManege/departmentReplacement/Index.vue'),
                    hidden: true,
                    meta: { title: '部门替换', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/teachingEvaluation',
            name: 'launch-demo2-teachingEvaluation',
            component: RouteView,
            hidden: true,
            meta: { title: '教学评估查询', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/teachingEvaluation/evaluationStatistics',
                    name: 'launch-demo2-teachingEvaluation-evaluationStatistics',
                    component: () => import('@/view/launch-demo2/teachingEvaluation/evaluationStatistics/Index.vue'),
                    hidden: true,
                    meta: { title: '评估统计', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingEvaluation/teachingAchievement',
                    name: 'launch-demo2-teachingEvaluation-teachingAchievement',
                    component: () => import('@/view/launch-demo2/teachingEvaluation/teachingAchievement/Index.vue'),
                    hidden: true,
                    meta: { title: '教学成绩查询', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingEvaluation/moduleManager',
                    name: 'launch-demo2-teachingEvaluation-moduleManager',
                    component: () => import('@/view/launch-demo2/teachingEvaluation/moduleManager/Index.vue'),
                    hidden: true,
                    meta: { title: '模块管理', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingEvaluation/overallEvaluation',
                    name: 'launch-demo2-teachingEvaluation-overallEvaluation',
                    component: () => import('@/view/launch-demo2/teachingEvaluation/overallEvaluation/Index.vue'),
                    hidden: true,
                    meta: { title: '整体评估设置', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/teachingEvaluation/specialCourse',
                    name: 'launch-demo2-teachingEvaluation-specialCourse',
                    component: () => import('@/view/launch-demo2/teachingEvaluation/specialCourse/Index.vue'),
                    hidden: true,
                    meta: { title: '专题课管理', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/courseQuery',
            name: 'launch-demo2-courseQuery',
            component: RouteView,
            hidden: true,
            meta: { title: '课程提纲', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/courseQuery/courseQuery',
                    name: 'launch-demo2-courseQuery-courseQuery',
                    component: () => import('@/view/launch-demo2/courseQuery/courseQuery/Index.vue'),
                    hidden: true,
                    meta: { title: '课程提纲', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/cassAuthority',
            name: 'launch-demo2-cassAuthority',
            component: RouteView,
            hidden: true,
            meta: { title: '班级权限', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/cassAuthority/permissionSetting',
                    name: 'launch-demo2-cassAuthority-permissionSetting',
                    component: () => import('@/view/launch-demo2/cassAuthority/permissionSetting/Index.vue'),
                    hidden: true,
                    meta: { title: '权限设置', keepAlive: true, icon: 'global' },
                },
            ],
        },
        {
            path: '/launch-demo2/workloadManager',
            name: 'launch-demo2-workloadManager',
            component: RouteView,
            hidden: true,
            meta: { title: '工作量管理', keepAlive: true, icon: 'global' },
            children: [
                {
                    path: '/launch-demo2/workloadManager/teacherWorkload',
                    name: 'launch-demo2-workloadManager-teacherWorkload',
                    component: () => import('@/view/launch-demo2/workloadManager/teacherWorkload/Index.vue'),
                    hidden: true,
                    meta: { title: '教师工作量', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/workloadManager/yearWorkload',
                    name: 'launch-demo2-workloadManager-yearWorkload',
                    component: () => import('@/view/launch-demo2/workloadManager/yearWorkload/Index.vue'),
                    hidden: true,
                    meta: { title: '年度工作量', keepAlive: true, icon: 'global' },
                },
                {
                    path: '/launch-demo2/workloadManager/peripheralWorkload',
                    name: 'launch-demo2-workloadManager-peripheralWorkload',
                    component: () => import('@/view/launch-demo2/workloadManager/peripheralWorkload/Index.vue'),
                    hidden: true,
                    meta: { title: '外围工作量', keepAlive: true, icon: 'global' },
                },
            ],
        },
    ],
};

export default constantRouters;
