import RacDomainApi from './rac/RacDomainApi';
import RacSysApi from './rac/RacSysApi';
import RacPermGroupApi from './rac/RacPermGroupApi';
import RacPermApi from './rac/RacPermApi';
import RacSignInApi from './rac/RacSignInApi';
import RacAgentSignInApi from './rac/RacAgentSignInApi';
import RacAgentSignOutApi from './rac/RacAgentSignOutApi';
import RacRoleApi from './rac/RacRoleApi';
import RacOrgApi from './rac/RacOrgApi';
import RacAccountApi from './rac/RacAccountApi';
import RacOpLogApi from './rac/RacOpLogApi';
import RacLockLogApi from './rac/RacLockLogApi';
import RacPermUrnApi from './rac/RacPermUrnApi';
import RacPermMenuApi from './rac/RacPermMenuApi';

export const racDomainApi = new RacDomainApi();
export const racSysApi = new RacSysApi();
export const racPermGroupApi = new RacPermGroupApi();
export const racPermApi = new RacPermApi();
export const racRoleApi = new RacRoleApi();
export const racOrgApi = new RacOrgApi();
export const racAccountApi = new RacAccountApi();
export const racSignInApi = new RacSignInApi();
export const racAgentSignInApi = new RacAgentSignInApi();
export const racAgentSignOutApi = new RacAgentSignOutApi();
export const racOpLogApi = new RacOpLogApi();
export const racLockLogApi = new RacLockLogApi();
export const racPermUrnApi = new RacPermUrnApi();
export const racPermMenuApi = new RacPermMenuApi();
